.\" Manpage for gatekeeper.
.TH man 8 "17 Dec 2014" "1.0" "gatekeeper man page"
.SH NAME
gatekeeper - run gate system to control access
.SH SYNOPSIS
gatekeeper [-v=1]
.SH DESCRIPTION
garekeeper is a system that control doors access
.SH OPTIONS
.IP -v verbosity
-v=1 - verbose, -v=0 - silent
.IP -stop
stop all daemons and executor
.SH SEE ALSO
man doord
.SH BUGS
No known bugs.
.SH AUTHOR
VEB GUNDYSCHWEIN KIRCHE EINSTIEGCONTROLLER GmbH.
